"""empty message

Revision ID: a2899c9dc081
Revises: 1191c16836a7
Create Date: 2024-05-28 12:26:00.454980

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2899c9dc081'
down_revision = '1191c16836a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post_comentarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_criacao', sa.DateTime(), nullable=True))
        batch_op.drop_column('data_criação')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post_comentarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_criação', sa.DATETIME(), nullable=True))
        batch_op.drop_column('data_criacao')

    # ### end Alembic commands ###
